export { DashboardPage } from './DashboardPage'
export { BudgetPage } from './BudgetPage'
export { IngredientsPage } from './IngredientsPage'
export { RecipesPage } from './RecipesPage'
export { CostPage } from './CostPage'
export { ProductionSimulatorPage } from './ProductionSimulatorPage'
export { ProfitabilityPage } from './ProfitabilityPage'
export { FixedCostsPage } from './FixedCostsPage'
export { PricingPage } from './PricingPage'
export { BreakEvenPage } from './BreakEvenPage'
export { SensitivityPage } from './SensitivityPage'
export { StockPage } from './StockPage'
export { CashflowPage } from './CashflowPage'
export { ReportsPage } from './ReportsPage'
export { ConfigPage } from './ConfigPage'

